service: nkuba-logistics-backend

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  profile: personal
  region: af-south-1
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
  timeout: 15
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: "*"

plugins:
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      dbPath: "dynamodb"
      migrate: true

package:
  individually: false
  excludeDevDependencies: true
  exclude:
    - .dynamodb/**

functions:
  - ${file(lambdas/endpoints/endpoints.yml)}

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: orders-table
